config/routes.rb
Rails.application.routes.draw do
 # get 'home/about'
 # root 'home#index'

  root "home#index"
  get '/home/:id/buy', to: 'home#buy', as: 'buy'
  get '/checkout', to: 'home#checkout', as: 'checkout'
  get 'home/about', to: 'home#about'
  get '/products.json', to: 'home#list', as: 'list'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :price, comparison: {greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    if session[:cart].nil?
        session[:cart] = []
    end
    @products = Product.all
    @cart = session[:cart]

end

def list
  @products = Product.all
  render json: @products, only: [:id, :name, :price, :stock]
end

def buy
  if session[:cart].nil?
    session[:cart] = []
  end
  product = Product.find(params[:id])
  session[:cart].append(product)
  redirect_to :root

end

def checkout
  @cart = session[:cart]
  session[:cart] = []

  @cart.each do |product|
    p = Product.find(product["id"])
    p.stock = p.stock - 1
    if(p.stock < 0)
      p.stock = 0
    end
    p.save
  end
end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container-fluid">
    <%= link_to 'Autodrone Store', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link"%>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/checkout.html.erb
<h2>Your cart:</h2>

<ul>
  <% @cart.each do |product| %>
    <li> <%=product["name"]%> </li>
  <% end %>
</ul>

<div class="alert alert-primary">
Your items are on the way!<div>

<a href="/">Keep Shopping</a>

app/views/home/index.html.erb
<h1>Hello World!</h1>
This is my first rails webpage!
<hr/>
<h2>There are <%= @cart.length %> items in your cart</h2>

<ul>
    <% @products.each do |product| %>
        <li>
            <strong><%=product.name%></strong> costs $<%=product.price%> dollars
            <br/>
            <%= image_tag(product.image, :size => '260x260') %>
            <br/>
            <%= product.description%>
            <br/>
            Stock: <%= product.stock%>
            <br/>
            <%if(product.stock > 0)%>
                <%= link_to "Buy Now", buy_path(product), class: "btn btn-primary" %>
            <%else%>
                <span class="badge bg-secondary">OUT OF STOCK</span>
            <%end%>
            <hr/>
        </li>
    <% end %>
</ul>

<%= @products.count %> products and counting!
<br/>
<a href="/checkout">Checkout</a>

<hr/>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-LP9K4H6HSR"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'G-LP9K4H6HSR');
    </script>

    <!-- Bootstrap CSS -->
   <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
-->
    <title>Autodrone Store</title>
     <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "bootstrap.min" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render 'home/header'%>
    <div class="container">
      <br/><br/>
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>